services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: patient_shiba_nudge_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    ports:
      - "3002:3002"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/patient_shiba_nudge_development
      RAILS_ENV: development
    volumes:
      - ./backend:/app
      - bundle_cache:/usr/local/bundle
    command: >
      bash -c "
        bundle install &&
        bundle exec rails db:create db:migrate db:seed &&
        bundle exec rails server -b 0.0.0.0 -p 3002
      "

volumes:
  postgres_data:
  bundle_cache: